### ISSUE TITLE
Code In Headers

### ISSUE THREAD

**Issue by gudenau** [CTCaer/jc_toolkit#1]
Actual code should never be in header files!

The point of them is to tell the compiler about data structures and symbols it can link against.

**Comment by CTCaer** [comment]
Well, normally yes and I also felt strange when the following happened:

Because it was the first time writing C++ WinForms, I just used the visual studio wizard to create the minimum necessary files. 
These were actually a stub .cpp that runs the form and a header that contains the actual form and its code. 
So I did what Microsoft proposed and because I didn't want using interfaces and public structures, I left it as it was and built everything forms related inside it.

Many things can be done to break the code to many smaller files and also even only a rename of the winforms header to cpp and a new header that define the form can also work.

Right now, I want to mostly do code deduplication  to functions that use the same things over and over and maybe use more structs to group data.
But I'm open to suggestions.
