### ISSUE TITLE
Troubling interacting with the MCU unit

### ISSUE THREAD

**Issue by Yamakaky** [CTCaer/jc_toolkit#44]
Posting here since that's the only tool I found that managed to use the IR sensor.

I'm trying to interact with the IR/NFC unit following the process in [`ir_sensor()`](https://github.com/CTCaer/jc_toolkit/blob/master/jctool/jctool.cpp#L1672). I already have working code for the accelerometer, buttons and joysticks including calibration from SPI. For the MCU, I'm stuck at step 2 (check status). I get a `0x31` (standard + IMU + MCU) report, but with `buf[49] == 0xff` instead of `0x01`. Is there some additional steps required before calling ir_sensor? Couldn't find anything from your code. A push in the right direction would be appreciated.

My code is at https://github.com/Yamakaky/joy/blob/master/src/hid.rs#L168.

Pinging @jon-dez since they seem more active.

**Comment by CTCaer** [comment]
If buf[49] is 0xFF then MCU is disabled or the command was sent to a Left Joycon.
Otherwise you sent wrong command.

That byte is basically the MCU report id.

I can't remember specifics to be true, but you can find my unfinished documentation here:
https://github.com/CTCaer/Nintendo_Switch_Reverse_Engineering/blob/ir-nfc/mcu_ir_nfc_notes.md

**Comment by Yamakaky** [comment]
OK, so I found out I needed to re-send the MCU status request in loop like you do in your code. I guess it needs some time to warm up. Thanks for your link, it will be useful!
